title:   Jennifer Eyring
logo: "/images/github logo2.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <b>Data Analyst & Visualization Specialist</b>
  <br>
  Empowering Buisnesses through their data 
  <br><br>
  <a href="https://www.linkedin.com/in/jennifereyring/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
