title: Jennifer Eyring
logo: "/2020-10-23 14.34.53-2.jpg?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst & Visualization Specialist 
  <br><br>
  Empowering Buisnesses through their data 
  <br><br>
  <a href="https://www.linkedin.com/in/jennifereyring/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
